version: 2.1
jobs:
  build-and-test:
    docker:
      - image: node:13-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
